CREATE TABLE PostLikes (
    Id INT IDENTITY PRIMARY KEY,
    PostId INT NOT NULL,
    UserId INT NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (PostId) REFERENCES Posts(Id),
    FOREIGN KEY (UserId) REFERENCES Users(Id),
    CONSTRAINT UC_PostLike UNIQUE (PostId, UserId)
);