
CREATE TABLE Posts (
    Id INT IDENTITY PRIMARY KEY,
    UserId INT NOT NULL,
    Title VARCHAR(200) NOT NULL,
    Content VARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    IsFlagged BIT NOT NULL DEFAULT 0,
    FlagReason VARCHAR(200) NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);
